manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Keep the personal fork remote available in case we need to roll back.
    - name: oleksandrmaslov
      url-base: https://github.com/oleksandrmaslov
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 904c9aec8822d79149d42c8a9a77e8828eb08f5a
      import: app/west.yml
    - name: zmk-soft-off-plus
      remote: oleksandrmaslov
      revision: dcd452b4f2dc9b2f9e285df16ea3a7b54c2d8b6b
    - name: zmk-split-hid-display
      remote: oleksandrmaslov
      revision: ab5e2a72a8ac4039ed472a5a280b60cd955b0cf5
  self:
    path: config
